#!/bin/bash

# display home screen

HOME_SCR=`cat src/screen/home.scr`

STAT=1

while [ $STAT = 1 ]
do

	printf "\ec"
	printf "$HOME_SCR"

	read -rsn1 INPUT

	case $INPUT in
		a)
			./src/about
			;;
		q)
			STAT=0
			;;
		h)
			./src/help
			;;
		[1-9])
			REF=`printf "%02d" $INPUT`
			./src/mat-display src/materials/$REF/
	esac
done

printf "\ec"
